package cm4108.user.model;
//Author: S M ABDULLAH FERDOUS
//Cloud computing coursework

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import cm4108.config.*;

@DynamoDBTable(tableName="requests")
public class requests {
	
	private String id;
	private String requestFrom;
	private String requestTo;
	private  long updatetime;
	
public requests()
{
} //end method

public requests(String requestFrom, String requestTo, long updatetime) {
	
	
	this.setRequestFrom(requestFrom);
	this.setRequestTo(requestTo);
	this.setUpdatetime(updatetime);
}


//---------------------------------------------------------------
@DynamoDBHashKey(attributeName="id")
@DynamoDBAutoGeneratedKey
public String getId() {
	return id;
} //end method

public void setId(String id) {
	this.id = id;
} //end method
//-----------------------------------------------------------------
@DynamoDBAttribute(attributeName="requestFrom")
public String getRequestFrom() {
	return requestFrom;
}

public void setRequestFrom(String requestFrom) {
	this.requestFrom = requestFrom;
}

//------------------------------------------------------------------
@DynamoDBAttribute(attributeName="requestTo")
public String getRequestTo() {
	return requestTo;
}

public void setRequestTo(String requestTo) {
	this.requestTo = requestTo;
}
//-------------------------------------------------------------------
@DynamoDBAttribute(attributeName="Timestamp")
public long getUpdatetime() {
	return updatetime;
}

public void setUpdatetime(long updatetime) {
	this.updatetime = updatetime;
}
	

	
	
	

}
